/*
 * Database connection for the IKONEX API.
 *
 * Production/dev: Microsoft SQL Server (e.g. localhost\SQLEXPRESS) via the
 * `mssql` package, using a SQL login from server/.env:
 *
 *   DB_SERVER=localhost
 *   DB_INSTANCE=SQLEXPRESS        # named instance (uses SQL Server Browser)
 *   DB_PORT=                      # or a fixed TCP port instead of the instance name
 *   DB_NAME=ikonex
 *   DB_USER=ikonex_app
 *   DB_PASSWORD=...
 *   DB_ENCRYPT=false
 *   DB_TRUST_SERVER_CERTIFICATE=true
 *
 * Tests only: DB_CLIENT=sqlite with DB_FILE (uses Node's built-in node:sqlite).
 *
 * Every query goes through `db.query(sql, params)` with @named parameters.
 * The few spots where T-SQL and SQLite differ are generated by `db.d.*`.
 */

const env = (k, d = "") => (process.env[k] ?? d).toString().trim();

// ---------------------------------------------------------------------------
// Dialects
// ---------------------------------------------------------------------------
const mssqlDialect = {
  name: "mssql",
  now: "SYSUTCDATETIME()",
  /** INSERT … returning the new Id as column "Id" */
  insert: (table, cols) =>
    `INSERT INTO ${table} (${cols.join(", ")}) OUTPUT INSERTED.Id VALUES (${cols
      .map((c) => "@" + c)
      .join(", ")})`,
  page: (orderBy) => `ORDER BY ${orderBy} OFFSET @offset ROWS FETCH NEXT @limit ROWS ONLY`,
  top: (n) => `TOP (${Number(n)})`,
  limit: () => "",
  dateOnly: (col) => `CAST(${col} AS date)`,
  daysAgo: (n) => `DATEADD(day, -${Number(n)}, CAST(SYSUTCDATETIME() AS date))`,
  startOfMonth: "DATEFROMPARTS(YEAR(SYSUTCDATETIME()), MONTH(SYSUTCDATETIME()), 1)",
  today: "CAST(SYSUTCDATETIME() AS date)",
  like: (param) => `LIKE @${param}`,
};

const sqliteDialect = {
  name: "sqlite",
  now: "strftime('%Y-%m-%dT%H:%M:%fZ','now')",
  insert: (table, cols) =>
    `INSERT INTO ${table.replace(/^dbo\./, "")} (${cols.join(", ")}) VALUES (${cols
      .map((c) => "@" + c)
      .join(", ")}) RETURNING Id`,
  page: (orderBy) => `ORDER BY ${orderBy} LIMIT @limit OFFSET @offset`,
  top: () => "",
  limit: (n) => `LIMIT ${Number(n)}`,
  dateOnly: (col) => `date(${col})`,
  daysAgo: (n) => `date('now','-${Number(n)} days')`,
  startOfMonth: "date('now','start of month')",
  today: "date('now')",
  like: (param) => `LIKE @${param}`,
};

// ---------------------------------------------------------------------------
// Adapters
// ---------------------------------------------------------------------------
const toParam = (v) => {
  if (v === undefined) return null;
  if (typeof v === "boolean") return v ? 1 : 0;
  if (v instanceof Date) return v.toISOString();
  return v;
};

async function createMssql() {
  let sql;
  try {
    sql = (await import("mssql")).default;
  } catch (e) {
    throw new Error(
      "The 'mssql' package is not installed. Run `npm install` in the project folder."
    );
  }

  const port = env("DB_PORT");
  const config = {
    server: env("DB_SERVER", "localhost"),
    database: env("DB_NAME", "ikonex"),
    user: env("DB_USER"),
    password: env("DB_PASSWORD"),
    ...(port ? { port: Number(port) } : {}),
    options: {
      ...(port ? {} : env("DB_INSTANCE") ? { instanceName: env("DB_INSTANCE") } : {}),
      encrypt: env("DB_ENCRYPT", "false") === "true",
      trustServerCertificate: env("DB_TRUST_SERVER_CERTIFICATE", "true") === "true",
      enableArithAbort: true,
    },
    pool: { max: 10, min: 0, idleTimeoutMillis: 30000 },
    connectionTimeout: 15000,
    requestTimeout: 30000,
  };

  // Create the database itself if it doesn't exist yet (connects to master)
  if (env("DB_AUTO_CREATE", "true") === "true") {
    const master = new sql.ConnectionPool({ ...config, database: "master" });
    await master.connect();
    const name = config.database.replace(/]/g, "]]");
    await master
      .request()
      .input("name", sql.NVarChar, config.database)
      .query(`IF DB_ID(@name) IS NULL EXEC('CREATE DATABASE [${name}]')`);
    await master.close();
  }

  const pool = new sql.ConnectionPool(config);
  await pool.connect();

  return {
    d: mssqlDialect,
    describe: `SQL Server ${config.server}${
      config.options.instanceName ? "\\" + config.options.instanceName : ""
    }${port ? ":" + port : ""} / ${config.database}`,
    async query(text, params = {}) {
      const request = pool.request();
      for (const [k, v] of Object.entries(params)) request.input(k, toParam(v));
      const result = await request.query(text);
      return result.recordset || [];
    },
    async exec(text) {
      await pool.request().batch(text);
    },
    async close() {
      await pool.close();
    },
  };
}

async function createSqlite() {
  const { DatabaseSync } = await import("node:sqlite");
  const file = env("DB_FILE", ":memory:");
  const db = new DatabaseSync(file);
  db.exec("PRAGMA foreign_keys = ON;");
  return {
    d: sqliteDialect,
    describe: `SQLite ${file} (test mode)`,
    async query(text, params = {}) {
      const p = {};
      // only pass parameters the statement actually uses
      for (const [k, v] of Object.entries(params)) if (text.includes("@" + k)) p[k] = toParam(v);
      const stmt = db.prepare(text);
      if (/^\s*(select|with)\b|\breturning\b/i.test(text)) {
        return stmt.all(p).map((r) => ({ ...r }));
      }
      stmt.run(p);
      return [];
    },
    async exec(text) {
      db.exec(text);
    },
    async close() {
      db.close();
    },
  };
}

export const dbConfigured = () =>
  env("DB_CLIENT") === "sqlite" || Boolean(env("DB_SERVER") && env("DB_USER"));

export async function connectDb() {
  if (env("DB_CLIENT") === "sqlite") return createSqlite();
  return createMssql();
}
